[platformio]
default_envs = main

[env:main]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_protocol = arduino
upload_speed = 115200
upload_port = COM4
upload_flags = -D
monitor_speed = 9600
monitor_port = COM4
lib_deps =
    nRF24/RF24